apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-service-mybtc
spec:
  selector:
    matchLabels:
      app: api-auth-service-mybtc
  template:
    metadata:
      labels:
        app: api-auth-service-mybtc
    spec:
      containers:
        - name: api-auth-service-mybtc
          image: paulohsv/api-auth-service-mybtc:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http