apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybtc-auth-service
spec:
  selector:
    matchLabels:
      app: mybtc-auth-service
  template:
    metadata:
      labels:
        app: mybtc-auth-service
    spec:
      containers:
        - name: mybtc-auth-service
          image: paulohsv/mybtc-auth-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http