apiVersion: v1
kind: Service
metadata:
  name: api-auth-service-mybtc
spec:
  selector:
    app: api-auth-service-mybtc
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer