name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  20.10.0
     
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
  
      - name: Test and Coverage
        run: npm run test:cov
       
         
