name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  20.10.0
     
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
  
      - name: Test and Coverage
        run: npm run test:cov
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      - name: Build Docker Image
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/my_btc_auth:${{github.sha}}
      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/my_btc_auth:${{github.sha}}


         
